// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2DjKi-vQ81d8V08XUA9tivQno6n00wr4',
    appId: '1:640025952063:web:fbcf08a3923c06c7505d8a',
    messagingSenderId: '640025952063',
    projectId: 'oprs-349a6',
    authDomain: 'oprs-349a6.firebaseapp.com',
    storageBucket: 'oprs-349a6.appspot.com',
    measurementId: 'G-WT7GT1ZR1L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS6_8DaycZs85FJgLyBVfHg0krTT-EJf4',
    appId: '1:640025952063:android:53285a22e719380d505d8a',
    messagingSenderId: '640025952063',
    projectId: 'oprs-349a6',
    storageBucket: 'oprs-349a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIpiOqGKRX3sDhScoKgXadv0UpxokwyBA',
    appId: '1:640025952063:ios:398039b25970b4a7505d8a',
    messagingSenderId: '640025952063',
    projectId: 'oprs-349a6',
    storageBucket: 'oprs-349a6.appspot.com',
    iosBundleId: 'com.example.oprs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIpiOqGKRX3sDhScoKgXadv0UpxokwyBA',
    appId: '1:640025952063:ios:96948f408649b1de505d8a',
    messagingSenderId: '640025952063',
    projectId: 'oprs-349a6',
    storageBucket: 'oprs-349a6.appspot.com',
    iosBundleId: 'com.example.oprs.RunnerTests',
  );
}
